### ISSUE TITLE
Could not open library './libpd.so'

### ISSUE THREAD

**Issue by mikewinters10** [mgsx-dev/pd-offline#1]
Trying to figure out how this could be adapted for a Mac. I follow all of the instructions in the ReadMe.md, except 
`cp libpd/libs/libpd.so pd-offline/libpd.so`

becomes
`cp libpd/libs/libpd.dylib pd-offline/libpd.dylib `

Then when I try to run the example code
`ruby pd-generate.rb example generate.pd example/sample.wav 2 44100 1.5`

I get an error:
```
/usr/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library './libpd.so': dlopen(./libpd.so, 5): image not found (LoadError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/mikewinters/Desktop/pd-offline/lib/pd.rb:6:in `<class:Pd>'
	from /Users/mikewinters/Desktop/pd-offline/lib/pd.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mikewinters/Desktop/pd-offline/lib/pd-batch.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Any Mac specific instructions? Thanks for this great tool!

**Comment by mikewinters10** [comment]
Happy to answer my own question thanks to some people who know better than me.

In the file /lib/pd.rb, change line 6 to `ffi_lib "./libpd.dylib"`

That fixes it for me.

**Comment by mgsx-dev** [comment]
Sorry, I'm working mostly on linux and then there still some hard coded stuff which make it not usable on some platforms.

I'll try to improve things a little to make it work on all platforms.

Thanks for the issue.

**Comment by mgsx-dev** [comment]
I've fixed it and update documentation.

OS should be detect automatically now, could you please test it on your Mac, I don't have Mac myself :-). Don't forget to install dependencies after pulling, see update section I've just added in readme file.

Thanks.

**Comment by mikewinters10** [comment]
Just checked, works like a charm on my Mac OSX 10.11.
